### PR TITLE
Adapt SybilItem.getparent to handle Session objects

### PR DESCRIPTION
**Pull request by nicoddemus**
Initial attempt to fix pytest-dev/pytest#2979

### CODE REVIEW

**Comment by nicoddemus** [comment]
@cjw296 it seems the error reported in pytest-dev/pytest#2979 is fixed, but the failures are now different.

**Comment by cjw296** [comment]
@nicoddemus - the remaining failures were in tests that make sure the output of running sybil tests under pytest is as helpful as possible. Looks like 3.3 changed that output, so I had to fix in 487c8608d64c5a2a81ea37592482800ff80bddef.

Kind of surprised that's not a command line option? That kind of progress reporting is really unpleasant when using CI tools like Jenkins.

**Comment by nicoddemus** [comment]
> Kind of surprised that's not a command line option? That kind of progress reporting is really unpleasant when using CI tools like Jenkins.

IMHO it looks nice, except perhaps if you are using `-v` with somewhat long file names, as seems to be the case in sybil's test suite: https://travis-ci.org/cjw296/sybil/jobs/309386414. Is this what you mean?

For example pytest's own test run looks nice: https://travis-ci.org/pytest-dev/pytest/jobs/309237898

If people really would like to change the default back, it is certainly something we can do in a future release if more people prefer it.

**Comment by cjw296** [comment]
@nicoddemus - I was referring to the need to do this:

```
[pytest]
console_output_style = classic
```

...in `pytest.ini` rather than having a command line option to do the same.

**Comment by nicoddemus** [comment]
Oh I see. There's the `-o` command-line option that can alter `ini` options, so you can do this: `pytest -o console_output_style=classic`. 😉 

If this is something people would like to do on the command-line frequently we can surely consider adding an explicit option for it. Decided to introduce only an ini option for now and see if the demand arises (after all is easy to add an option, but much more complex to remove it later).

**Pull request merged**
